### ISSUE TITLE
WInキーやCtrlキーで動作するようにならないでしょうか

### ISSUE THREAD

**Issue by AkiraSS** [t-kouyama/ConvertAndNonConvertEmulator#1]
Windows機で、Mac用のUSキーボードを使っています。
スペースキーの両側にWinキー(Commandキー)があります。
　↓
[Ctrl]   [Alt]   [Win]   [Space]   [Win]   [Alt]   [Ctrl]
 
左 Win キー＝無変換キー、右 Winキー＝変換キーとして動作するよう、設定を変えることはできませんか。

また、ConvertAndNonCovertEmulator と Autohotkey が併用できる場合には、
 Ctrl と WIn キーを入れ替えて、左Ctrlキー＝無変換、右Ctrl＝変換として使いたいです。

※会社PCで使うためAdministrator権限がなく、レジストリでキーの入れ替えができません。
※Alt-ime-ahkのスクリプトでは、キー入れ替え表記と共存できませんでした。

ご検討のほどよろしくお願いいたします。

**Comment by t-kouyama** [comment]
無変換/変換キーとして使用できるキーを Windows キーや Ctrl キーなどに変更できるようにしました。

AutoHotkey と併用した場合ですが、簡単に試した限りでは AutoHotkey のリマップ機能を使って入れ替えたキーには ConvertAndNonCovertEmulator が反応しないようでした。
両ソフトが使用する内部処理の違いで必ず ConvertAndNonCovertEmulator が先に処理されるからではないかと思うので、今のところ対応は難しいです。

**Comment by t-kouyama** [comment]
無変換/変換キーとして使用できるキーを Windows キーや Ctrl キーなどに変更できるようにしました。

AutoHotkey と併用した場合ですが、簡単に試した限りでは AutoHotkey のリマップ機能を使って入れ替えたキーには ConvertAndNonCovertEmulator が反応しないようでした。
内部処理の違いから必ず ConvertAndNonCovertEmulator が先に処理されることが原因ではないかと思うので、これについては今のところ対応は難しいです。

**Comment by AkiraSS** [comment]
t-kouyama 様

機能を追加いただきありがとうございました。
スペースキーの両側のコマンドキー(Winキー)で変換、無変換の制御ができるようになり大変快適になりました。

AutoHotKeyとの共存が難しい件、了解いたしました。
いつの日か、レジストリを使わないでキーのリマップができるようなプログラムを自分でも作れるよう、頑張りたいと思います。

どうもありがとうございました。
